all: opengl tex

LDFLAGS+=-L$(SDKSTAGE)/opt/vc/lib/ -lGLESv2 -lEGL -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpthread -lrt -L../libs/ilclient -L../libs/vgfont
INCLUDES+=-I$(SDKSTAGE)/opt/vc/include/ -I$(SDKSTAGE)/opt/vc/include/interface/vcos/pthreads -I$(SDKSTAGE)/opt/vc/include/interface/vmcs_host/linux -I./ -I../libs/ilclient -I../libs/vgfont

opengl: opengl.c
	gcc $(INCLUDES) $(LDFLAGS) opengl.c -o opengl
tex: tex.c
	gcc $(INCLUDES) $(LDFLAGS) tex.c -o tex
clean:
	rm -rf *.o

